import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Invictos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/invictos.png" />
      </Head>

      <div className='flex justify-center h-screen bg-black text-white'>
        <div className='flex flex-col justify-center gap-2'>
          <Image src="/invictos.svg" alt="Vercel Logo" width={100} height={100} />
          <p className='text-white text-center text-3xl'>Invictos</p>
        </div>
      </div>
    </div>
  )
}
