import Head from 'next/head'
import { Introduction } from '../components/Introduction'
import { signIn, signOut, useSession } from 'next-auth/react'

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <div>
        <Head>
          <title>Invictos</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/invictos.png" />
        </Head>
      </div>
      {!session && (
        <Introduction />
      )}
      {session && (
        <div className='flex justify-center items-center h-screen bg-black'>
          <button className='px-3 py-2 rounded bg-purple-dark text-white' onClick={() => signOut()}>Sair</button>
        </div>
      )}
    </>
  )
}
